spring.application.name=backend-api

server.port=8084

# Swagger UI settings
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/v3/api-docs

# Grouping multiple services in Swagger UI
springdoc.swagger-ui.urls[0].name=Orchestration
springdoc.swagger-ui.urls[0].url=/v3/api-docs

springdoc.swagger-ui.urls[1].name=Authentication
springdoc.swagger-ui.urls[1].url=http://localhost:8080/v3/api-docs

springdoc.swagger-ui.urls[2].name=Chat Service
springdoc.swagger-ui.urls[2].url=http://localhost:8082/v3/api-docs

springdoc.swagger-ui.urls[3].name=User Service
springdoc.swagger-ui.urls[3].url=http://localhost:8081/v3/api-docs


jwt.secret=q5FjgWSxQsC1XzCp890HTctN/TjwB3PE6AcUfT8V6mYKsozZ/vCmfafYiO6UgUJalMbyw60gM4BcwRMt5tvAJA==
jwt.expiration-ms=3600000
services.face-detection.url=http://chat-service:8082/api/llm/analyze
services.llm-fastapi.url=http://coordinator:8000/analyze
services.llm.spring.chat.url=http://chat-service:8082/api/llm/chat
services.llm.spring.transcribe.url=http://chat-service:8082/api/llm/transcribe
services.chat.creation.url=http://chat-service:8082/api/chats/chatController/create
services.chat.getter.url=http://chat-service:8082/api/chats/chatController/byUser
services.chat.history.url=http://chat-service:8082/api/chats/history/getAll
services.chat.history.create.url=http://chat-service:8082/api/chats/history/create
services.kp-agent.url=http://kp-service:8000/api/v1/chat

services.auth.reg.url=http://authentication-service:8080/api/auth/register
services.user.reg.url=http://user-service:8081/api/users/register
services.auth.del.url=http://authentication-service:8080/api/auth/delete/
services.auth.log.url=http://authentication-service:8080/api/auth/login

logging.level.org.springframework.security=DEBUG
??????????? ? ????????
logging:
level:
root: INFO
com.pdiagnosis: DEBUG  # ???? ????? ? ??? ????? ????????????
org.springframework.web: DEBUG
org.springframework.web.client: DEBUG
org.springframework.security: DEBUG
httpclient.wire: DEBUG  # ??????? HTTP-????????? ? ????
org.apache.http: DEBUG

pattern:
console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
file:
name: /app/logs/backend-api.log  # ???? ?????? ??????????
max-size: 10MB
max-history: 7

use-console-colors: false