CREATE TABLE IF NOT EXISTS DocumentType (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TypeName VARCHAR(50) UNIQUE NOT NULL
);
INSERT INTO DocumentType (TypeName) VALUES ('Приказ'), ('Распоряжение'), ('Указание') ON CONFLICT (TypeName) DO NOTHING;

CREATE TABLE IF NOT EXISTS Company (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(100) NOT NULL UNIQUE,
    LegalAddress VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS Department (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    HierarchyLevel INT NOT NULL,
    ParentDepartmentID INT NULL,
    FOREIGN KEY (ParentDepartmentID) REFERENCES Department(ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Correspondent (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Position VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Employee (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Position VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Document (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Number VARCHAR(50) NOT NULL UNIQUE,
    CreationDate DATE NOT NULL,
    ReleaseDate DATE NOT NULL,
    Content TEXT NOT NULL,
    DocumentTypeID INT NOT NULL, -- Новое поле
    SignerPosition VARCHAR(100) NOT NULL,
    SignerFullName VARCHAR(100) NOT NULL,
    FOREIGN KEY (DocumentTypeID) REFERENCES DocumentType(ID)
);

CREATE TABLE IF NOT EXISTS Event (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Deadline DATE NOT NULL,
    CompletionDate DATE NULL,
    IsCompleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS DocumentCorrespondent (
    CorrespondentID INT NOT NULL,
    DocumentID INT NOT NULL,
    AuthorAssignmentDate DATE NOT NULL,
    PRIMARY KEY (CorrespondentID, DocumentID),
    FOREIGN KEY (CorrespondentID) REFERENCES Correspondent(ID) ON DELETE CASCADE,
    FOREIGN KEY (DocumentID) REFERENCES Document(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DocumentEvent (
    DocumentID INT NOT NULL,
    EventID INT NOT NULL,
    SequenceNumber INT NOT NULL,
    PRIMARY KEY (DocumentID, EventID),
    FOREIGN KEY (DocumentID) REFERENCES Document(ID) ON DELETE CASCADE,
    FOREIGN KEY (EventID) REFERENCES Event(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EventAssignment (
    EventID INT NOT NULL,
    EmployeeID INT NOT NULL,
    AssignmentDate DATE NOT NULL,
    Priority VARCHAR(50) NOT NULL,
    PRIMARY KEY (EventID, EmployeeID),
    FOREIGN KEY (EventID) REFERENCES Event(ID) ON DELETE CASCADE,
    FOREIGN KEY (EmployeeID) REFERENCES Employee(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DocumentSigning (
    EmployeeID INT NOT NULL,
    DocumentID INT NOT NULL,
    SigningDate DATE NOT NULL,
    SignStatus VARCHAR(50) NOT NULL,
    PRIMARY KEY (EmployeeID, DocumentID),
    FOREIGN KEY (EmployeeID) REFERENCES Employee(ID) ON DELETE CASCADE,
    FOREIGN KEY (DocumentID) REFERENCES Document(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CorrespondentDepartment (
    CorrespondentID INT NOT NULL,
    DepartmentID INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NULL,
    Status VARCHAR(50) NOT NULL,
    PRIMARY KEY (CorrespondentID, DepartmentID),
    FOREIGN KEY (CorrespondentID) REFERENCES Correspondent(ID) ON DELETE CASCADE,
    FOREIGN KEY (DepartmentID) REFERENCES Department(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EmployeeDepartment (
    EmployeeID INT NOT NULL,
    DepartmentID INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NULL,
    Status VARCHAR(50) NOT NULL,
    PRIMARY KEY (EmployeeID, DepartmentID),
    FOREIGN KEY (EmployeeID) REFERENCES Employee(ID) ON DELETE CASCADE,
    FOREIGN KEY (DepartmentID) REFERENCES Department(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DepartmentCompany (
    DepartmentID INT NOT NULL,
    CompanyID INT NOT NULL,
    InclusionDate DATE NOT NULL,
    PRIMARY KEY (DepartmentID, CompanyID),
    FOREIGN KEY (DepartmentID) REFERENCES Department(ID) ON DELETE CASCADE,
    FOREIGN KEY (CompanyID) REFERENCES Company(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DepartmentEvent (
    DepartmentID INT NOT NULL,
    EventID INT NOT NULL,
    AssignmentDate DATE NOT NULL,
    ResponsibilityLevel VARCHAR(50) NOT NULL,
    PRIMARY KEY (DepartmentID, EventID),
    FOREIGN KEY (DepartmentID) REFERENCES Department(ID) ON DELETE CASCADE,
    FOREIGN KEY (EventID) REFERENCES Event(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EventControl (
    EmployeeID INT NOT NULL,
    EventID INT NOT NULL,
    ControlStartDate DATE NOT NULL,
    Frequency VARCHAR(50) NOT NULL,
    PRIMARY KEY (EmployeeID, EventID),
    FOREIGN KEY (EmployeeID) REFERENCES Employee(ID) ON DELETE CASCADE,
    FOREIGN KEY (EventID) REFERENCES Event(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_document_creation_date ON Document(CreationDate);
CREATE INDEX IF NOT EXISTS idx_document_type ON Document(DocumentTypeID); -- Изменено
CREATE INDEX IF NOT EXISTS idx_event_deadline ON Event(Deadline);
CREATE INDEX IF NOT EXISTS idx_event_completion_date ON Event(CompletionDate);
CREATE INDEX IF NOT EXISTS idx_event_is_completed ON Event(IsCompleted);
CREATE INDEX IF NOT EXISTS idx_document_event_sequence ON DocumentEvent(SequenceNumber);
CREATE INDEX IF NOT EXISTS idx_event_assignment_priority ON EventAssignment(Priority);
CREATE INDEX IF NOT EXISTS idx_document_signing_status ON DocumentSigning(SignStatus);

